
# the services part
services:
#nginx
  nginx:
    image: nginx:user
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

#mariadb
  mariadb:
    image: mariadb:user
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file :
      - .env
    networks :
      - inception
    volumes:
      - mariadb:/var/lib/mysql
#wordpress
  wordpress:
    image: wordpress:user
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    env_file :
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

#wordpress volume
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aben-nei/data/wordpress/

#mariadb volume
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aben-nei/data/mariadb/

# the networks part
networks:
  inception:
    name: inception