# the services part
services:
#nginx
  nginx:
    image: nginx
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

#mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file :
      - .env
    networks :
      - inception
    volumes:
      - mariadb:/var/lib/mysql
#wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    env_file :
      - .env
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

#adminer
  adminer:
    image: adminer
    build: ./requirements/bonus/adminer/
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inception

#website
  website:
    image: website
    build: ./requirements/bonus/website/
    container_name: website
    ports:
      - "8000:8000"
    networks:
      - inception
#portainer
  portainer:
    image: portainer
    build: ./requirements/bonus/portainer/
    container_name: portainer
    ports:
      - "6443:6443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception

volumes:
#wordpress volume
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/aben-nei/data/wordpressVM
      o: bind
      type: none
# mariadb volume
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/aben-nei/data/mariadbVM
      o: bind
      type: none

# the networks part
networks:
  inception:
    name: inception